{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

---
{{- if not .Values.localnode.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "validator.fullname" . }}-dapp
  labels: {{- include "validator.labels" . | nindent 4 }}
data:
  "dapp.json": |
    {
        "address": {{ required "A valid .Values.dapp.contractAddress is required" .Values.dapp.contractAddress | quote }},
        "blockHash": {{ required "A valid .Values.dapp.blockHash is required" .Values.dapp.blockHash | quote }},
        "blockNumber": {{ required "A valid .Values.dapp.blockNumber is required" .Values.dapp.blockNumber | int64 | quote }},
        "transactionHash": {{ required "A valid .Values.dapp.transactionHash is required" .Values.dapp.transactionHash | quote }}
    }
{{ end -}}
