{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

{{- if .Values.postgresql.enabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "validator.fullname" . }}-database-config
  labels: {{- include "validator.labels" . | nindent 4 }}
data:
  POSTGRES_HOSTNAME: {{ .Release.Name }}-postgresql
  POSTGRES_PORT: {{ .Values.postgresql.auth.port | quote }}
  POSTGRES_USER: {{ required "A valid .Values.postgresql.auth.username is required" .Values.postgresql.auth.username }}
  POSTGRES_DB: {{ required "A valid .Values.postgresql.auth.database is required" .Values.postgresql.auth.database }}
{{- end }}
