{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "validator.fullname" . }}-database
  labels: {{- include "validator.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_ENDPOINT: {{ include "validator.postgresEndpoint" . | b64enc | quote }}

