{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "validator.fullname" . }}-dispatcher
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "validator.selectorLabels" . | nindent 6 }}
      rollups.cartesi.io/component: dispatcher
  template:
    metadata:
      {{- with .Values.dispatcher.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "validator.selectorLabels" . | nindent 8 }}
        rollups.cartesi.io/component: dispatcher
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "validator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.dispatcher.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.dispatcher.initContainers }}
        {{- include "tplvalues.render" ( dict "value" .Values.dispatcher.initContainers "context" $ ) | nindent 8 }}
        {{- end }}
      containers:
        - name: rollups-dispatcher
          image: {{ include "dispatcher.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.dispatcher.resources | nindent 12 }}
          {{- if .Values.dispatcher.command }}
          command:
          {{- include "tplvalues.render" (dict "value" .Values.dispatcher.command "context" $) | nindent 12 }}
          {{- end }}
          args:
            - {{ print "--sc-grpc-endpoint=http://" (include "validator.fullname" .) "-state-server:50051" | quote }}
            {{- if .Values.dispatcher.healthCheck.enabled }}
            - {{ print "--http-server-port=" (default .Values.dispatcher.healthCheck.port 8081) | quote }}
            {{- end }}
            {{- if .Values.localnode.enabled }}
            - --rd-rollups-deployment-file=/opt/cartesi/share/deployments/localhost.json
            - --rd-dapp-deployment-file=/deployments/localhost/dapp.json
            {{- else }}
            - {{ print "--rd-rollups-deployment-file=/opt/cartesi/share/deployments/" (required "A valid .Values.dapp.network is required" .Values.dapp.network | replace "-" "_") ".json" | quote }}
            - {{ print "--rd-dapp-deployment-file=/deployments/" (required "A valid .Values.dapp.network is required" .Values.dapp.network | replace "-" "_") "/dapp.json" | quote }}
            {{- end }}
            {{- if (or .Values.dapp.mnemonic.value .Values.dapp.mnemonic.secretRef .Values.localnode.enabled) }}
            - {{ print "--auth-mnemonic-file=/var/run/secrets/mnemonic/MNEMONIC" | quote }}
            {{- end }}
            {{- if .Values.localnode.enabled }}
            - --tx-provider-http-endpoint=http://{{ include "validator.fullname" . }}-localnode:8545
            {{- else }}
            - {{ print "--tx-provider-http-endpoint=" (required "A valid .Values.dapp.httpProvider is required" .Values.dapp.httpProvider) | quote }}
            {{- end }}
            {{- if (or .Values.dapp.network .Values.localnode.enabled) }}
            - {{ print "--tx-chain-id=" (include "dapp.chainID" .) | quote }}
            {{- end }}
            - {{ print (include "validator.redisConfig" .) | quote }}
            {{- range .Values.dispatcher.args }}
            - {{ . | quote}}
            {{- end }}
            {{- range .Values.dispatcher.extraArgs }}
            - {{ . | quote}}
            {{- end }}
          {{- if .Values.dispatcher.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ (default 8081 .Values.dispatcher.healthCheck.port) }}
            initialDelaySeconds: 3
          {{- end }}
          env:
            - name: RUST_LOG
              value: {{ .Values.dispatcher.logLevel }}
            {{- if .Values.dispatcher.extraEnvVars }}
            {{- include "tplvalues.render" (dict "value" .Values.dispatcher.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if or .Values.dispatcher.extraEnvVarsCM .Values.dispatcher.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.dispatcher.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "tplvalues.render" ( dict "value" .Values.dispatcher.extraEnvVarsCM "context" $ ) }}
            {{- end }}
            {{- if .Values.dispatcher.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "tplvalues.render" ( dict "value" .Values.dispatcher.extraEnvVarsSecret "context" $ ) }}
            {{- end }}
          {{- end }}
          volumeMounts:
            {{- if (or .Values.dapp.mnemonic.value .Values.localnode.enabled .Values.dapp.mnemonic.secretRef) }}
            - name: mnemonic
              mountPath: /var/run/secrets/mnemonic
              readOnly: true
            {{- end }}
            - name: dispatcher-lib
              mountPath: /opt/cartesi/rollups-dispatcher/lib
              readOnly: false
            {{- if .Values.localnode.enabled }}
            - name: blockchain-data
              mountPath: /opt/cartesi/share/deployments
              readOnly: false
            - name: deployments
              mountPath: /deployments
              readOnly: false
            {{- else }}
            - name: dapp
              mountPath: "/deployments/{{ .Values.dapp.network }}/"
              readOnly: true
            {{- end}}
            {{- if .Values.dispatcher.extraVolumeMounts }}
            {{- include "tplvalues.render" ( dict "value" .Values.dispatcher.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}

      volumes:
        {{- if .Values.localnode.enabled }}
        - name: blockchain-data
          persistentVolumeClaim:
            claimName: {{ include "validator.fullname" . }}-blockchain-data-pvc
        - name: deployments
          persistentVolumeClaim:
            claimName: {{ include "validator.fullname" . }}-deployments-pvc
        {{- end }}
        - name: dispatcher-lib
          emptyDir: {}
        - name: dapp
          configMap:
            name: "{{ include "validator.fullname" . }}-dapp"
            items:
              - key: "dapp.json"
                path: "dapp.json"
        {{- if (or .Values.dapp.mnemonic.value .Values.localnode.enabled .Values.dapp.mnemonic.secretRef) }}
        - name: mnemonic
          secret:
            {{- if (or .Values.dapp.mnemonic.value .Values.localnode.enabled) }}
            secretName: {{ include "validator.fullname" . }}-mnemonic
            {{- else }}
            secretName: {{ .Values.dapp.mnemonic.secretRef }}
            {{- end }}
        {{- end }}
        {{- if .Values.dispatcher.extraVolumes }}
        {{- include "tplvalues.render" ( dict "value" .Values.dispatcher.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
      {{- with .Values.dispatcher.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dispatcher.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dispatcher.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
