{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "validator.fullname" . }}-dispatcher
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "validator.selectorLabels" . | nindent 6 }}
      rollups.cartesi.io/component: dispatcher
  template:
    metadata:
      {{- with .Values.dispatcher.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "validator.selectorLabels" . | nindent 8 }}
        rollups.cartesi.io/component: dispatcher
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "validator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.dispatcher.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.dispatcher.initContainers }}
        {{- include "tplvalues.render" ( dict "value" .Values.dispatcher.initContainers "context" $ ) | nindent 8 }}
        {{- end }}
      containers:
        - name: rollups-dispatcher
          image: {{ include "dispatcher.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.dispatcher.resources | nindent 12 }}
          {{- if .Values.dispatcher.command }}
          command:
          {{- include "tplvalues.render" (dict "value" .Values.dispatcher.command "context" $) | nindent 12 }}
          {{- end }}
          args:
            - {{ print "--sc-grpc-endpoint=http://" (include "validator.fullname" .) "-state-server:50051" | quote }}
            {{- if .Values.dispatcher.healthCheck.enabled }}
            - {{ print "--http-server-port=" (default .Values.dispatcher.healthCheck.port 8081) | quote }}
            {{- end }}
            - {{ print "--dapp-address=" (required "A valid .Values.dapp.contractAddress is required" .Values.dapp.contractAddress) | quote }}
            - {{ print "--dapp-deploy-block-hash=" (required "A valid .Values.dapp.blockHash is required" .Values.dapp.blockHash) | quote }}
            {{- if .Values.dapp.network }}
            - {{ print "--chain-id=" (include "dapp.chainID" .) | quote }}
            {{- end }}
            {{- range .Values.dispatcher.args }}
            {{- end }}
            {{- range .Values.dispatcher.extraArgs }}
            - {{ . | quote}}
            {{- end }}
          {{- if .Values.dispatcher.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ (default 8081 .Values.dispatcher.healthCheck.port) }}
            initialDelaySeconds: 3
          {{- end }}
          env:
            - name: RUST_LOG
              value: {{ .Values.dispatcher.logLevel }}
            {{- if .Values.dispatcher.extraEnvVars }}
            {{- include "tplvalues.render" (dict "value" .Values.dispatcher.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if or .Values.dispatcher.extraEnvVarsCM .Values.dispatcher.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.dispatcher.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "tplvalues.render" ( dict "value" .Values.dispatcher.extraEnvVarsCM "context" $ ) }}
            {{- end }}
            {{- if .Values.dispatcher.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "tplvalues.render" ( dict "value" .Values.dispatcher.extraEnvVarsSecret "context" $ ) }}
            {{- end }}
          {{- end }}
          volumeMounts:
            {{- if (or .Values.dapp.mnemonic.value .Values.dapp.mnemonic.secretRef) }}
            - name: mnemonic
              mountPath: /var/run/secrets/mnemonic
              readOnly: true
            {{- end }}
            {{- if .Values.dispatcher.extraVolumeMounts }}
            {{- include "tplvalues.render" ( dict "value" .Values.dispatcher.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}

      volumes:
        {{- if (or .Values.dapp.mnemonic.value .Values.dapp.mnemonic.secretRef) }}
        - name: mnemonic
          secret:
            {{- if .Values.dapp.mnemonic.value }}
            secretName: {{ include "validator.fullname" . }}-mnemonic
            {{- else }}
            secretName: {{ .Values.dapp.mnemonic.secretRef }}
            {{- end }}
        {{- end }}
        {{- if .Values.dispatcher.extraVolumes }}
        {{- include "tplvalues.render" ( dict "value" .Values.dispatcher.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
      {{- with .Values.dispatcher.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dispatcher.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dispatcher.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
