{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "validator.fullname" . }}-inspect-server
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.inspectServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "validator.selectorLabels" . | nindent 6 }}
      rollups.cartesi.io/component: inspect-server
  template:
    metadata:
      labels:
        {{- include "validator.selectorLabels" . | nindent 8 }}
        rollups.cartesi.io/component: inspect-server
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "validator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.inspectServer.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.inspectServer.initContainers }}
        {{- include "tplvalues.render" ( dict "value" .Values.inspectServer.initContainers "context" $ ) | nindent 8 }}
        {{- end }}
      containers:
        - name: rollups-inspect-server
          image: {{ include "inspectServer.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.inspectServer.resources | nindent 12 }}
          {{- if .Values.inspectServer.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ default 8084 .Values.inspectServer.healthCheck.port }}
            initialDelaySeconds: 3
          {{- end }}
          {{- if .Values.inspectServer.command }}
          command:
          {{- include "tplvalues.render" (dict "value" .Values.inspectServer.command "context" $) | nindent 12 }}
          {{- end }}
          args:
            - {{ print "--server-manager-address=" (include "validator.fullname" .) "-server-manager:5001" }}
            {{- if .Values.inspectServer.healthCheck.enabled }}
            - {{ print "--healthcheck-port=" (default 8084 .Values.inspectServer.healthCheck.port) | quote }}
            {{- end }}
            {{- range .Values.inspectServer.args }}
            - {{ . | quote}}
            {{- end }}
            {{- range .Values.inspectServer.extraArgs }}
            - {{ . | quote}}
            {{- end }}
          env:
            - name: RUST_LOG
              value: {{ .Values.inspectServer.logLevel }}
            {{- if .Values.inspectServer.extraEnvVars }}
            {{- include "tplvalues.render" (dict "value" .Values.inspectServer.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if or .Values.inspectServer.extraEnvVarsCM .Values.inspectServer.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.inspectServer.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "tplvalues.render" ( dict "value" .Values.inspectServer.extraEnvVarsCM "context" $ ) }}
            {{- end }}
            {{- if .Values.inspectServer.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "tplvalues.render" ( dict "value" .Values.inspectServer.extraEnvVarsSecret "context" $ ) }}
            {{- end }}
          {{- end }}
          volumeMounts:
            {{- if .Values.inspectServer.extraVolumeMounts }}
            {{- include "tplvalues.render" ( dict "value" .Values.inspectServer.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 5005

      {{- with .Values.inspectServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.inspectServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.inspectServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        {{- if .Values.inspectServer.extraVolumes }}
        {{- include "tplvalues.render" ( dict "value" .Values.inspectServer.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
