{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

{{- if .Values.localnode.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "validator.fullname" . }}-localnode
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "validator.selectorLabels" . | nindent 6 }}
      rollups.cartesi.io/component: localnode
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.localnode.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "validator.selectorLabels" . | nindent 8 }}
        rollups.cartesi.io/component: localnode
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "validator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.localnode.podSecurityContext | nindent 8 }}
      initContainers:
        - name: anvilstate
          image: sunodo/rollups-node:0.2.0
          command:
            - cp
            - /opt/cartesi/share/deployments/anvil_state.json
            - /opt/cartesi/share/deployments/localhost.json
            - /opt/anvil/
          volumeMounts:
            - name: blockchain-data
              mountPath: /opt/anvil
              readOnly: false
      containers:
        - name: anvil
          image: {{ include "anvil.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.localnode.anvil.resources | nindent 12 }}
          {{- if .Values.localnode.anvil.command }}
          command:
          {{- include "tplvalues.render" (dict "value" .Values.localnode.anvil.command "context" $) | nindent 12 }}
          {{- end}}
          args:
            {{- range .Values.localnode.anvil.args }}
            - {{ . | quote}}
            {{- end }}
            {{- range .Values.localnode.anvil.extraArgs }}
            - {{ . | quote}}
            {{- end }}
          livenessProbe:
            exec:
              command:
                - eth_isready
            initialDelaySeconds: 12
          env:
            - name: ANVIL_IP_ADDR
              value: "0.0.0.0"
            {{- if .Values.localnode.anvil.extraEnvVars }}
            {{- include "tplvalues.render" (dict "value" .Values.localnode.anvil.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 8545
          volumeMounts:
            - name: blockchain-data
              mountPath: /opt/cartesi/share/deployments
              readOnly: false
            - name: deployments
              mountPath: /app/rollups/deployments
              readOnly: false
      volumes:
        - name: blockchain-data
          persistentVolumeClaim:
            claimName: {{ include "validator.fullname" . }}-blockchain-data-pvc
        - name: deployments
          persistentVolumeClaim:
            claimName: {{ include "validator.fullname" . }}-deployments-pvc
{{- end }}