{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

{{- if .Values.validator.config.CARTESI_AUTH_MNEMONIC }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.fullname" . }}-mnemonic
  labels: {{- include "validator.labels" . | nindent 4 }}
type: Opaque
data:
  MNEMONIC: {{ .Values.validator.config.CARTESI_AUTH_MNEMONIC | b64enc }}
{{- end }}
