{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

{{- if (or .Values.dapp.mnemonic.value .Values.localnode.enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.fullname" . }}-mnemonic
  labels: {{- include "validator.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.localnode.enabled }}
stringData:
  MNEMONIC: "test test test test test test test test test test test junk"
{{- else }}
data:
  MNEMONIC: {{ .Values.dapp.mnemonic.value | b64enc }}
{{- end }}
{{- end }}
