{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}-validator
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.validator.service.type }}
  ports:
    - port: {{ .Values.validator.service.port }}
      targetPort: {{ .Values.validator.config.CARTESI_HTTP_PORT }}
      protocol: TCP
      name: rollups-node
  selector:
    {{- include "validator.selectorLabels" . | nindent 4 }}
