{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}-validator
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.validator.service.type }}
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: graphql-server
    - port: 5005
      targetPort: 5005
      protocol: TCP
      name: inspect-server
  selector:
    {{- include "validator.selectorLabels" . | nindent 4 }}
