{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}-state-server
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.stateServer.service.type }}
  ports:
    - port: {{ .Values.stateServer.service.port }}
      targetPort: 50051
      protocol: TCP
      name: state-server
  selector:
    {{- include "validator.selectorLabels" . | nindent 4 }}
    rollups.cartesi.io/component: state-server
