---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: applications.rollups.cartesi.io
spec:
    group: rollups.cartesi.io
    names:
        kind: Application
        listKind: ApplicationList
        plural: applications
        singular: application
    scope: Namespaced
    versions:
        - name: v1
          schema:
              openAPIV3Schema:
                  description: Application is the Schema for the applications API
                  properties:
                      apiVersion:
                          description:
                              "APIVersion defines the versioned schema of this representation
                              of an object. Servers should convert recognized schemas to the latest
                              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
                          type: string
                      kind:
                          description:
                              "Kind is a string value representing the REST resource this
                              object represents. Servers may infer this from the endpoint the client
                              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
                          type: string
                      status:
                          description: Status defines the observed state of DApp
                          type: object
                      metadata:
                          type: object
                      spec:
                          description: Spec defines the desired state of DApp
                          type: object
                          properties:
                              address:
                                  description: Address of the application
                                  type: string
                              blockHash:
                                  description: Block hash of the block which deployed the application
                                  type: string
                              blockNumber:
                                  description: Block number of the block which deployed the application
                                  type: string
                              transactionHash:
                                  description: Transaction hash of the transaction which deployed the application
                                  type: string
                              location:
                                  description: Location of the cartesi machine snapshot
                                  type: string
                  type: object
          served: true
          storage: true
          subresources:
              status: {}
