# (c) Cartesi and individual authors (see AUTHORS)
# SPDX-License-Identifier: Apache-2.0 (see LICENSE)

apiVersion: v2
name: rollups-node-chart
description: A Helm chart for a Cartesi Rollups Validator Node
maintainers:
  - name: endersonmaia
    email: endersonmaia@gmail.com
    url: https://github.com/endersonmaia
  - name: oap75
    email: omid.asadpoor36@gmail.com
    url: https://github.com/oap75

type: application
version: 1.3.1-0
