{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "validator.fullname" . }}-endpoints
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.endpoints.replicaCount }}
  selector:
    matchLabels:
      {{- include "validator.selectorLabels" . | nindent 6 }}
      rollups.cartesi.io/component: endpoints
  template:
    metadata:
      labels:
        {{- include "validator.selectorLabels" . | nindent 8 }}
        rollups.cartesi.io/component: endpoints
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "validator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.endpoints.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.endpoints.initContainers }}
        {{- include "tplvalues.render" ( dict "value" .Values.endpoints.initContainers "context" $ ) | nindent 8 }}
        {{- end }}
      containers:
        - name: rollups-inspect-server
          image: {{ include "inspectServer.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.endpoints.inspectServer.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5005
            initialDelaySeconds: 3
          args:
            {{- range .Values.endpoints.inspectServer.args }}
            - {{ . | quote}}
            {{- end }}
            {{- range .Values.endpoints.inspectServer.extraArgs }}
            - {{ . | quote}}
            {{- end }}
          env:
            - name: RUST_LOG
              value: {{ .Values.endpoints.inspectServer.logLevel }}
            {{- if .Values.endpoints.inspectServer.extraEnvVars }}
            {{- include "tplvalues.render" (dict "value" .Values.endpoints.inspectServer.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if or .Values.endpoints.inspectServer.extraEnvVarsCM .Values.endpoints.inspectServer.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.endpoints.inspectServer.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "tplvalues.render" ( dict "value" .Values.endpoints.inspectServer.extraEnvVarsCM "context" $ ) }}
            {{- end }}
            {{- if .Values.endpoints.inspectServer.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "tplvalues.render" ( dict "value" .Values.endpoints.inspectServer.extraEnvVarsSecret "context" $ ) }}
            {{- end }}
          {{- end }}
          volumeMounts:
            {{- if .Values.endpoints.inspectServer.extraVolumeMounts }}
            {{- include "tplvalues.render" ( dict "value" .Values.endpoints.inspectServer.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 5005

        - name: graphql-server
          image: {{ include "graphqlServer.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.endpoints.graphqlServer.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 3
          env:
            - name: RUST_LOG
              value: {{ .Values.endpoints.graphqlServer.logLevel }}
            {{- if .Values.endpoints.graphqlServer.extraEnvVars }}
            {{- include "tplvalues.render" (dict "value" .Values.endpoints.graphqlServer.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
            - name: GRAPHQL_HOST
              value: "0.0.0.0"
            - name: GRAPHQL_PORT
              value: "4000"
            {{- if .Values.postgresql.enabled }}
            - name: POSTGRES_PASSWORD_FILE
              value: /var/run/secrets/postgres/PASSWORD
            {{- end }}
          envFrom:
            {{- if .Values.postgresql.enabled }}
            - configMapRef:
                name: {{ include "validator.fullname" . }}-database-config
            {{- end }}
          {{- if or .Values.endpoints.graphqlServer.extraEnvVarsCM .Values.endpoints.graphqlServer.extraEnvVarsSecret }}
            {{- if .Values.endpoints.graphqlServer.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "tplvalues.render" ( dict "value" .Values.endpoints.graphqlServer.extraEnvVarsCM "context" $ ) }}
            {{- end }}
            {{- if .Values.endpoints.graphqlServer.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "tplvalues.render" ( dict "value" .Values.endpoints.graphqlServer.extraEnvVarsSecret "context" $ ) }}
            {{- end }}
          {{- end }}
          volumeMounts:
            {{- if .Values.postgresql.enabled }}
            - name: postgres
              mountPath: /var/run/secrets/postgres
              readOnly: true
            {{- end }}
            {{- if .Values.endpoints.graphqlServer.extraVolumeMounts }}
            {{- include "tplvalues.render" ( dict "value" .Values.endpoints.graphqlServer.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 4000
      {{- with .Values.endpoints.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.endpoints.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.endpoints.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        {{- if .Values.postgresql.enabled }}
        - name: postgres
          secret:
            secretName: {{ include "validator.fullname" . }}-postgres
        {{- end }}
        {{- if .Values.endpoints.extraVolumes }}
        {{- include "tplvalues.render" ( dict "value" .Values.endpoints.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
