{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

{{- range .Values.extraDeploy }}
---
{{ include "tplvalues.render" (dict "value" . "context" $) }}
{{- end }}
