{{- if .Values.validator.localnode.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "validator.fullname" . }}-machine-snapshots-pvc
spec:
  storageClassName: {{ .Values.validator.localnode.storage.machineSnapshots.storageClass | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.validator.localnode.storage.machineSnapshots.size | quote}}
{{- end }}