{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.fullname" . }}-mnemonic
  labels: {{- include "validator.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.validator.localnode.enabled }}
stringData:
  MNEMONIC: "test test test test test test test test test test test junk"
{{- else }}
data:
  MNEMONIC: {{ required "A valid .Values.dapp.mnemonic.value is required" .Values.dapp.mnemonic.value | b64enc }}
{{- end }}
{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.fullname" . }}-postgres
  labels: {{- include "validator.labels" . | nindent 4 }}
type: Opaque
data:
  PASSWORD: {{ required "A valid .Values.postgresql.auth.password sholud is required" .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
