{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

{{- if .Values.dapp.mnemonic.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.fullname" . }}-mnemonic
  labels: {{- include "validator.labels" . | nindent 4 }}
type: Opaque
data:
  MNEMONIC: {{ .Values.dapp.mnemonic.value | b64enc }}
{{- else if empty .Values.dapp.mnemonic.secretRef -}}
{{- fail "One of .Values.dapp.mnemonic.value or .Values.dapp.mnemonic.secretRef should be defined." -}}
{{- end }}
{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.fullname" . }}-postgres
  labels: {{- include "validator.labels" . | nindent 4 }}
type: Opaque
data:
  PASSWORD: {{ required "A valid .Values.postgresql.auth.password sholud is required" .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}