{{- /*
(c) Cartesi and individual authors (see AUTHORS)
SPDX-License-Identifier: Apache-2.0 (see LICENSE)
*/}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}-graphql-server
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.endpoints.graphqlServer.service.type }}
  ports:
    - port: {{ .Values.endpoints.graphqlServer.service.port }}
      targetPort: 4000
      protocol: TCP
      name: graphql
  selector:
    {{- include "validator.selectorLabels" . | nindent 4 }}
    rollups.cartesi.io/component: endpoints
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}-inspect-server
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.endpoints.inspectServer.service.type }}
  ports:
    - port: {{ .Values.endpoints.inspectServer.service.port }}
      targetPort: 5005
      protocol: TCP
      name: inspect-server
  selector:
    {{- include "validator.selectorLabels" . | nindent 4 }}
    rollups.cartesi.io/component: endpoints
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}-server-manager
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serverManager.service.type }}
  ports:
    - port: {{ .Values.serverManager.service.port }}
      targetPort: 5001
      protocol: TCP
      name: server-manager
  selector:
    {{- include "validator.selectorLabels" . | nindent 4 }}
    rollups.cartesi.io/component: server-manager
{{- if .Values.validator.localnode.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}-localnode
  labels: {{- include "validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.validator.localnode.service.type }}
  ports:
    - port: {{ .Values.validator.localnode.service.port }}
      targetPort: 8545
      protocol: TCP
      name: localnode
  selector:
    {{- include "validator.selectorLabels" . | nindent 4 }}
    rollups.cartesi.io/component: localnode
{{- end }}
